### PR TITLE
Fix #47, #46 and #41 among other small issues

### LINKED ISSUE #41: [BUG] Repeater fielddtype is missing the translateable icon
screenshot from 2016-07-21 20-09-57

### LINKED ISSUE #46: Preview is broken due to _route_params?
For the preview route we use a query string to set the locale, so `_route_params` won't work there IIRC.

Introduced in #38, Self-assigning :)

Details
-------

 - Translate Version: master 
 - Install type: Extension Repository
 - Bolt Version: master

### LINKED ISSUE #47: Homepage redirect no longer working
Homepage redirect no longer working since the homepage gets a default _locale since #43.

Possible duplicate content issue since the same page will happily display on both `/` and `/{default_locale_here}` (with different canonicals).

Details
-------

 - Translate Version: master 
 - Install type: Extension Repository
 - Bolt Version: master

### PR DESCRIPTION
**Pull request by SahAssar**
* Fix request cycle issues with the default locale in the routing override
* Move the homepageredirect to the top of the routes, fixes #47
* Add requirements to all routes based on the locales configured to avoid DC issues
* fix a few typos/minor errors
* Change how we look for the locale param so that it is allowed in a query string (required for preview and editcontent), fixes #46
* Add in a js to add the icon to repeaters, fixes #41
* Actually get the localeSlug in the StorageListener, (ping @gawainlynch for better way to do it since it comes from the request)
* Fix PSR2 warning for line length
* Ensure consistent usage between `current.get('slug')` and `current.slug`

### CODE REVIEW

File: src/TranslateExtension.php [hunk 1]
```diff
@@ -114,7 +121,7 @@ function ($app) {
                 }
 
                 foreach ($config->getLocales() as $locale) {
-                    if ($localeSlug = $locale->getSlug()) {
+                    if ($localeSlug === $locale->getSlug()) {
```
Comment (GawainLynch) [inline src/TranslateExtension.php]: Oh… that! :wink:

**Comment by SahAssar** [comment]
@GawainLynch: It's the default slug if no locale is present in the request, but the request locale if one is present...

**Comment by SahAssar** [comment]
Alright this seems to be done for now, merging!
